hugovk/Pillow

PIL/JpegImagePlugin.py

rolling back gps exif support to match pre 3.0.0 results

---

.travis/after_success.sh

Test Codecov.io alongside Coveralls.io to see which is better.

Add Codecov

---

src/libImaging/Draw.c

See https://github.com/python-pillow/Pillow/pull/3094#discussion_r214529464

Removed less than condition

---

docs/installation.rst

If you've already considered this and declined, feel free to ignore.

Remove note about Python 3.0-3.4

---

docs/reference/ImageStat.rst

A suggestion for https://github.com/python-pillow/Pillow/pull/3661, as I find the original version hard to read.

Changed wording

---

Tests/test_imageqt.py

Helps https://github.com/python-pillow/Pillow/pull/4108

Removed deprecation test

---

.travis/install.sh

Helps https://github.com/python-pillow/Pillow/pull/4108

Do not install qt4

---

docs/installation.rst

Removed the last two prompts in the installation doc - for https://github.com/python-pillow/Pillow/pull/4214

Removed prompts

---

docs/installation.rst

Helps https://github.com/python-pillow/Pillow/pull/4437
Adds the `--upgrade` flag to other places in the documentation where Pillow is being installed.
Also capitalises Pillow.

Recommend upgrading Pillow

---

Tests/test_imagefile.py

Helps https://github.com/python-pillow/Pillow/pull/4567

Assert that warning is raised

---

Tests/test_file_apng.py

Adds test for https://github.com/python-pillow/Pillow/pull/4726

Added disposal test

---

requirements.txt

Helps https://github.com/python-pillow/Pillow/pull/4746

Remove requirement for Python >= 3.6

---

.github/workflows/test-docker.yml
.github/workflows/test-windows.yml
.github/workflows/test.yml

For https://github.com/python-pillow/Pillow/pull/4931#issuecomment-697201291

Mergify test - Add all successful report jobs for GHA

---

.github/workflows/test.yml

For https://github.com/python-pillow/Pillow/pull/5029
Manually set the bit depth to 24bpp to improve coverage.

Set XVFB bit depth

---

.github/workflows/macos-install.sh
.github/workflows/test.yml

For https://github.com/python-pillow/Pillow/pull/5666
I personally don't mind the longer build time

Install numpy on Python 3.10

---

docs/resources/css/dark.css

For https://github.com/python-pillow/Pillow/pull/6158
This might be a matter of opinion, but I think this is clearer.

Rearranged CSS

---

src/PIL/TiffImagePlugin.py

A change for https://github.com/python-pillow/Pillow/pull/6196

Variable in function should be snake_case

---

src/PIL/ImageFilter.py
src/PIL/SgiImagePlugin.py

Helps https://github.com/python-pillow/Pillow/pull/6196/
https://github.com/python-pillow/Pillow/pull/6196/files#diff-6f614bf5744032be26f6bedc6d17acf289ee6a25f3293abb62f60c8b7550cc3aL185 references the variable used in the previous line.

Cleanup: adjust names

---

Tests/test_color_lut.py
Tests/test_imagesequence.py
src/PIL/GribStubImagePlugin.py
src/PIL/ImImagePlugin.py
src/PIL/Image.py
src/PIL/ImageColor.py
src/PIL/ImageMorph.py
src/PIL/JpegImagePlugin.py
src/PIL/PaletteFile.py
src/PIL/XpmImagePlugin.py

I think this would be a reasonable addition to https://github.com/python-pillow/Pillow/pull/6195

Simplified index slicing

---

.github/workflows/test-windows.yml
depends/install_extra_test_images.sh

For https://github.com/python-pillow/Pillow/pull/6918

Switched to python-pillow repositories

---

.github/workflows/test-mingw.yml
.github/workflows/test-windows.yml
.gitignore

Suggestions for https://github.com/python-pillow/Pillow/pull/6918
Feel free to ignore the removing of the wget dependency if you'd rather list the dependency explicitly. I make this as a PR to demonstrate that it works without it.

Removed wget dependency from MinGW

---

.github/workflows/test-valgrind.yml

Suggestion for https://github.com/python-pillow/Pillow/pull/6991

Run valgrind tests when GitHub Actions file changes

---

docs/make.bat

Suggestion for https://github.com/python-pillow/Pillow/pull/7016#discussion_r1142898039

Fixed calling html target from htmlview

---

winbuild/README.md
winbuild/build.rst

Suggestion for https://github.com/python-pillow/Pillow/pull/7058, maintaining the use of different Python versions as per https://github.com/python-pillow/Pillow/pull/7004/files#r1141519296

Updated Python version in documentation

---

Makefile

Suggestion for https://github.com/python-pillow/Pillow/pull/7530

Black infers target-version from requires-python in pyproject.toml

---

src/PIL/Image.py
src/PIL/ImageFont.py

Suggestions for https://github.com/python-pillow/Pillow/pull/7750

Use os.path.realpath consistently when os.fspath is used

---

src/PIL/GdImageFile.py
src/PIL/_typing.py

See https://github.com/python-pillow/Pillow/pull/7750#discussion_r1482539074

Removed FileDescriptor

---

docs/releasenotes/2.7.0.rst
docs/releasenotes/3.1.1.rst
docs/releasenotes/5.1.0.rst
docs/releasenotes/6.2.0.rst
docs/releasenotes/6.2.1.rst
docs/releasenotes/6.2.2.rst
docs/releasenotes/7.1.0.rst
docs/releasenotes/8.1.1.rst
docs/releasenotes/8.4.0.rst
docs/releasenotes/9.0.0.rst
docs/releasenotes/9.1.0.rst
docs/releasenotes/9.1.1.rst
docs/releasenotes/9.2.0.rst
docs/releasenotes/9.3.0.rst
docs/releasenotes/9.5.0.rst

Suggestions for https://github.com/python-pillow/Pillow/pull/7885
Not really changes for your PR, but just more changes after https://github.com/python-pillow/Pillow/pull/7877

Update release notes

---

docs/dater.py

Suggestion for https://github.com/python-pillow/Pillow/pull/8001

Use subprocess.DEVNULL

---

docs/dater.py

Suggestion for https://github.com/python-pillow/Pillow/pull/8001

Use split instead of datetime

---

.clang-format
src/libImaging/GifEncode.c
src/libImaging/JpegEncode.c

Suggestion for https://github.com/python-pillow/Pillow/pull/8015

Do not indent goto labels

---

src/libImaging/FliDecode.c

See https://github.com/python-pillow/Pillow/pull/8015#discussion_r1582061712
Docker builds will fail at the moment, but https://github.com/python-pillow/docker-images/pull/207 and https://github.com/python-pillow/Pillow/pull/8023 should fix that.

Change comment style

---

winbuild/README.md
winbuild/build.rst

Suggestion for https://github.com/python-pillow/Pillow/pull/8183

Drop support for Python 3.8

---

setup.py

Suggestion for https://github.com/python-pillow/Pillow/pull/8181

Increment Python version check on Windows

---

docs/make.bat

Suggestion for https://github.com/python-pillow/Pillow/pull/8917

Removed changes

---

Tests/README.rst
docs/deprecations.rst
docs/reference/plugins.rst
docs/releasenotes/11.0.0.rst
docs/releasenotes/5.0.0.rst
docs/releasenotes/8.1.0.rst

Suggestions for https://github.com/python-pillow/Pillow/pull/8914

Updated headings

---

docs/make.bat

Suggestion for https://github.com/python-pillow/Pillow/pull/8933

Remove unused I18NSPHINXOPTS variable
