- docs/deprecations.rst
'is', 'and' and 'in' are bold in https://pillow-hugovk.readthedocs.io/en/add-deprecations-and-removals-docs/deprecations.html. See https://pillow-radarhere.readthedocs.io/en/add-deprecations-and-removals-docs/deprecations.html for the effect of this PR
> Stopped code highlighting

- docs/releasenotes/5.4.1.rst
Multiple IDAT chunks may be read before the `load_read` loop stops.
> Updated release notes

- Tests/test_imageqt.py
Removes the warning found at https://travis-ci.org/python-pillow/Pillow/jobs/493640404#L4261. It is no longer present in https://travis-ci.org/hugovk/Pillow/jobs/494072306#L4258
> Catch DeprecationWarning from initial import

- .github/workflows/test-windows.yml
- .github/workflows/test.yml
Maybe you've already considered this, but this PR moves the copy operation into a separate step, so that "Upload coverage" goes back to using codecov/codecov-action@v1, which is simpler.
> Keep codecov-action

- Tests/test_imagedraw.py
It's in master - https://github.com/python-pillow/Pillow/blob/master/Tests/test_imagedraw.py#L249-L259 - but not your branch. I presume you accidentally deleted it during merge.
> Restored test

- Tests/test_file_im.py
Helps https://github.com/python-pillow/Pillow/pull/4424
Why was the test failing? I would guess something to do with https://docs.python.org/3/library/tempfile.html
> Whether the name can be used to open the file a second time, while the named temporary file is still open, varies across platforms (it can be so used on Unix; it cannot on Windows NT or later).
Why does this change made the test pass? I don't know.
> Rearranged code for Windows

- Tests/test_image.py
- src/PIL/Image.py
- src/PIL/__init__.py
Suggestion for https://github.com/python-pillow/Pillow/pull/4494 - creates a class that inherits from `str` and raises a warning when used in common ways.
> Raise a DeprecationWarning when comparing PILLOW_VERSION

- Tests/test_imagefile.py
- docs/deprecations.rst
- src/PIL/ImageFile.py
Helps https://github.com/python-pillow/Pillow/pull/4536
This is in support of 1, keep `raise_ioerror` and raise a deprecation warning.
I was thinking that 2, making it private, would be not ideal if someone was creating their own plugin and found some need for it.
Then I found that TiffImagePlugin raises an OSError in the same way that ImageFile does/will - https://github.com/python-pillow/Pillow/blob/a8a4b9bfdbf36ab964f57b34d1e1733d232b6175/src/PIL/TiffImagePlugin.py#L1181-L1182. If not for the fact that we are concerned with backwards compatibility, I'd suggest we change the TiffImagePlugin line from `raise OSError(err)` to `ImageFile.raise_oserror(err)`.
So yes, I think the `raise_oserror` function could still be useful external to `ImageFile`.
> Raise DeprecationWarning on raise_ioerror

- Tests/test_pickle.py
- src/PIL/WebPImagePlugin.py
Helps https://github.com/python-pillow/Pillow/pull/4561
Thanks for the PR.
[`tobytes()` is called when pickling an image](https://github.com/python-pillow/Pillow/blob/e4fa234340f5b4c583bd17db7037ef560aa92e5f/src/PIL/Image.py#L690-L691),  so that means [it is loaded](https://github.com/python-pillow/Pillow/blob/e4fa234340f5b4c583bd17db7037ef560aa92e5f/src/PIL/Image.py#L705-L729). As a result, I don't think we need to call `_open` like [you suggested](https://github.com/python-pillow/Pillow/pull/4561#discussion_r410067067).
When you set `__loaded = -1` in this PR, I'm guessing you were looking at [`_reset`](https://github.com/python-pillow/Pillow/blob/e4fa234340f5b4c583bd17db7037ef560aa92e5f/src/PIL/WebPImagePlugin.py#L119-L123). But as I'm saying here, an unpickled image isn't reset, it's …
> Initialise __loaded = 0, removed initialisation of __physical_frame

- docs/reference/ImageCms.rst
Helps https://github.com/python-pillow/Pillow/pull/4768
> Updated documentation

- setup.py
Two suggested changes here.
1.
```python
prefix = os.path.normpath(sys.prefix)
if prefix:
```
Experimenting I find that `os.path.normpath` always returns a non-empty string.
```
>>> import os
>>> os.path.normpath("")
'.'
>>> os.path.normpath("/")
'/'
>>> os.path.normpath(".")
'.'
>>> os.path.normpath("..")
'..'
>>> os.path.normpath("a")
'a'
```
So the `if` condition would always be true, and can therefore be removed.
2.
`prefix` is run through `os.path.join` and then used as the `subdir` argument to `_add_directory`.
https://github.com/python-pillow/Pillow/blob/e5415ca082e9dbecb5f1c21650303b680ce6cadd/setup.py#L206-L209
```python
def _add_directory(path, subdir, where=None):
if subdir is None:
return
subdir = os.path.realpath(subdir)
```
So it is immediately run through …
> Simplified code

- docs/deprecations.rst
- docs/releasenotes/8.0.0.rst
Suggestion for python-pillow/Pillow#4845:
* Use shorter links to make the `.rst` files easier to read.
From https://www.sphinx-doc.org/en/master/usage/restructuredtext/domains.html#cross-referencing-python-objects (emphasis mine):
>Also, if the name is prefixed with a dot, and no exact match is found, the target is taken as a suffix and all object names with that suffix are searched. For example, :py:meth:`.TarFile.close` references the tarfile.TarFile.close() function, even if the current module is not tarfile. **Since this can get ambiguous, if there is more than one possible match, you will get a warning from Sphinx.**
>
>**Note that you can combine the ~ and . prefixes: :py:meth:`~.TarFile.close` will reference the tarfile.TarFile.close() method, but the visible link caption will only …
> Simplify ImageCms links in docs

- Tests/test_imagefont.py
For https://github.com/python-pillow/Pillow/pull/5060
FreeType 2.3 is no longer tested, remove its metrics.
Related to https://github.com/python-pillow/Pillow/pull/4746#issuecomment-659313021
> Remove FreeType 2.3 metrics

- RELEASING.md
- Tests/helper.py
- Removed mention of Travis from Tests/helper.py
- Add mention of GitHub Actions to RELEASING for pillow-wheels
> Travis cleanup

- src/PIL/ImageFont.py
Suggestion for https://github.com/python-pillow/Pillow/pull/5098
In the PR, `packaging` is used to check the FreeType version. However, `packaging` isn't necessarily installed. Instead of adding a requirement for a new module just to allow users to see a DeprecationWarning if they have an older FreeType, this PR just abandons the DeprecationWarning if `packaging` is not installed.
> Do not require packaging just for a DeprecationWarning

- docs/resources/css/dark.css
- docs/resources/css/light.css
- docs/resources/js/script.js
Helps https://github.com/python-pillow/Pillow/pull/5056
While we're there, fix 3rd level menu item - see https://pillow--5056.org.readthedocs.build/en/5056/reference/ImageShow.html in dark mode, vs https://pillow-radarhere.readthedocs.io/en/fix-4th-level-menu-dark-mode/reference/ImageShow.html
> Fix 3rd level menu item background-color in dark mode

- docs/releasenotes/7.1.0.rst
- docs/releasenotes/8.1.0.rst
Helps https://github.com/python-pillow/Pillow/pull/5301
Makes a change that you made to the 8.1.1 release notes, in other locations.
> Expanded "OOB" to "out-of-bounds"

- docs/conf.py
For https://github.com/python-pillow/Pillow/pull/5498
https://pillow--5498.org.readthedocs.build/en/5498/handbook/tutorial.html lists 'og:image:alt' as 'Tutorial'.
That doesn't seem right to me.
This PR makes it 'Pillow' everywhere - https://pillow-radarhere.readthedocs.io/en/improve-docs/handbook/tutorial.html
> Set og:image:alt to be constant

- src/PIL/ImageQt.py
Suggestion to simplify https://github.com/python-pillow/Pillow/pull/5775
> Use QIODevice instead of QIODeviceBase

- Makefile
An idea to invoke more commands in Makefile through python3, rather than by themselves.
Considering
https://github.com/hugovk/Pillow/blob/75028b6f9369801bd8b973ccbb441abab4036a1c/Makefile#L77
this seems like it could prevent installing a setup.cfg requirement, only to have a different version later used by the Makefile.
I'm copying part of this idea from
https://github.com/hugovk/Pillow/blob/75028b6f9369801bd8b973ccbb441abab4036a1c/Makefile#L99
> Use python3 to run and install commands in Makefile

- Makefile
- docs/Makefile
- docs/releasenotes/9.1.0.rst
Helps https://github.com/python-pillow/Pillow/pull/6072
> Removed deprecated install-venv

- Tests/test_deprecate.py
- src/PIL/_deprecate.py
An idea for https://github.com/python-pillow/Pillow/pull/6184. Feel free to disregard if you want, as it is rather theoretical.
What if we managed to accidentally leave in a Pillow 10 deprecation warning for the Pillow 10 release?
Users would then be told that the feature would be removed in Pillow 10, with a date in the past, which would introduce confusion.
Or worse, we might have removed the `when == 10` condition, and they would receive a ValueError.
Instead, we could switch to the generic statement that it would be removed in "a future version".
> If removal version has arrived, raise an error

- docs/installation.rst
Suggestion for https://github.com/python-pillow/Pillow/pull/6764
The indentation for "In Fedora, the command is" and "In Alpine, the command is" does not match the indentation for "In Debian or Ubuntu".
> Changed indentation to be consistent

- src/PIL/ImImagePlugin.py
- src/PIL/Image.py
- src/PIL/ImageCms.py
- src/PIL/ImageFile.py
- src/PIL/ImageMorph.py
- src/PIL/PdfParser.py
- winbuild/build_prepare.py
Suggestions for https://github.com/python-pillow/Pillow/pull/6836
> Further improve exception traceback readability

- .github/workflows/test.yml
For https://github.com/python-pillow/Pillow/pull/6944
I found that removing the `file` filter allows CodeCov to detect the gcov files.
> add gcov coverage to test.yml

- Tests/test_qt_image_toqimage.py
- docs/reference/Image.rst
- src/PIL/Image.py
- src/PIL/MicImagePlugin.py
Suggestions for https://github.com/python-pillow/Pillow/pull/7059
- Update a comment that part of our test code fails on Qt5, as [it still fails with Qt6](https://github.com/radarhere/Pillow/actions/runs/4642710805/jobs/8216843788).
- Removed `_category` in connection to https://github.com/python-pillow/Pillow/pull/5351
- In connection to https://github.com/python-pillow/Pillow/pull/5954 / https://github.com/python-pillow/Pillow/pull/6830, removed documentation
> Remove deprecations for Pillow 10.0.0

- RELEASING.md
Suggestions for https://github.com/python-pillow/Pillow/pull/7074
Like https://github.com/python-pillow/Pillow/pull/7074/commits/9b0008627bb9d4f82ca353d653c2e85bab729a62, except for the other release types.
> Move "git push" commands later

- .pre-commit-config.yaml
- setup.py
- winbuild/README.md
- winbuild/build.rst
Suggestions for https://github.com/python-pillow/Pillow/pull/7190
- Apply code changes in documentation
- Updated pyproject-fmt to 0.12.1
- Removed now unused code
> Wrap arguments before passing in documentation

- winbuild/build_prepare.py
Suggestion for https://github.com/python-pillow/Pillow/pull/7407
In your PR at the moment,
```python
def cmd_nmake(
makefile: str | None = None,
target: str = "",
params: str | list[str] | tuple[str, ...] = None,
) -> str:
if params is None:
params = ""
elif isinstance(params, (list, tuple)):
params = " ".join(params)
else:
params = str(params)
```
`params` is either a string, list or tuple. When it is a string, `str(params)` is called? I find this odd, since it is already a string.
`cmd_nmake` is only called either without the third argument, or with a list, so maybe the simplest solution is just to restrict it to those two options?
> Restrict "params" to list or None

- docs/releasenotes/8.3.1.rst
Suggestion for https://github.com/python-pillow/Pillow/pull/7512
> Docs: link exceptions to Python docs

- docs/conf.py
- docs/resources/js/activate_tab.js
Suggestions for https://github.com/python-pillow/Pillow/pull/7579
- Do not test for iOS. We don't have an iOS tab
- Update a comment now that we're no longer searching for text "containing" the OS
- `window.navigator?.userAgentData` is used, after `window.navigator.userAgent` is used. So there's no point having the second `window.navigatior` be optional
- You've introduced `html_js_files`, so I've moved the existing CSS file into `html_css_files`
> Do not test for iOS

- docs/releasenotes/10.2.0.rst
Suggestion for https://github.com/python-pillow/Pillow/pull/7665
At the moment, speed is described as either '[] times as fast', '[]x as fast' or '[]% faster'.
This changes it to be consistent.
> Use consistent language

- .github/workflows/wheels.yml
Suggestions for https://github.com/python-pillow/Pillow/pull/7690
- Use the shorter, and more general, `CIBW_ARCHS` instead of `CIBW_ARCHS_LINUX`
- Combine build steps by including a condition in env variables
> Combine build steps

- docs/installation/basic-installation.rst
- docs/installation/building-from-source.rst
- docs/installation/python-support.rst
Suggestion for https://github.com/python-pillow/Pillow/pull/7858
```
.. _Building on Linux:
.. _Building on macOS:
.. _Building on Windows:
.. _Building on Windows using MSYS2/MinGW:
.. _Building on FreeBSD:
.. _Building on Android:
```
and
```
.. _Linux Installation:
.. _macOS Installation:
.. _Windows Installation:
.. _FreeBSD Installation:
```
are anchors that were added in https://github.com/python-pillow/Pillow/commit/e3a46fcfd0111d7f080da0efe5846 to replace headings.
I think they're not needed in these new locations. If someone was linking to https://pillow.readthedocs.io/en/stable/installation.html#building-on-windows-using-msys2-mingw, it's not going to do any good for us to add that anchor at building-from-source.html, as it's a different page.
> Simplified anchors

- .ci/install.sh
- .github/workflows/test.yml
Suggestion for https://github.com/python-pillow/Pillow/pull/8200
At the moment, 3.13-dev installs 3.13.0b2+, and 3.13 installs 3.13.0b2.
In a few months, 3.13-dev will become the same as 3.13. So it seems to me we can just remove the '-dev' suffix now and get it over with.
> Check GIL, rather than Python version

- src/_imagingft.c
This fixes the segfault.
`PyList_GetItemRef` crashes when used immediately after `PyList_New`. Not sure if this should be supported or not, so I changed it. I'll open a CPython issue as well.
> Don't use PyList_GetItemRef immediately after PyList_New

- docs/deprecations.rst
Suggestion for https://github.com/python-pillow/Pillow/pull/8356
The deprecations are currently sorted with the most recent at the bottom.
> Group 11.0.0 deprecations

- pyproject.toml
https://github.com/python-pillow/Pillow/pull/8514#discussion_r1831341942
> coverage vs coverage>=7.4.2: before, theoretically we could have installed coverage older than 7.4.2 here. I think that was unlikely and it's safer to require the newer version.
I'm a little confused, because the current state of the PR relaxes the coverage requirement, but
> But if we want to run it, trove-classifiers>=2024.10.12 is a required dependency. We shouldn't really just hope we end up with a newer one installed into the system.
is an argument that we shouldn't relax requirements?
This PR requires coverage>=7.4.2 in pyproject.toml, to be consistent.
> Require coverage>=7.4.2
